---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ml-secret
  namespace: ml
spec:
  encryptedData:
    OPENSEARCH_PASSWORD: AgAFnEAoT1+lthbGDCLqFE8pHQqOWh25IcYf6JZfufx8JBU8M/ZRlmFAaHjohlFXwhunfdCHbzUhSMGvPB9WK4JGvSqzdXBfVfjjMFkPnS64mX7NSGXJjDv4qGiDM89rxdtr1umC5HAYBZ+r6j0A3wuirG+f7DXsvbuCZv+Ag7q20pa33xlwxUv1XDbSatC8hMAGDgImkyJRDJZlnlhNlSgsNQm3TMGI1GsayuTMltINTunz+gykjYZcMOOJSIoCGe5FiJgrSGM47c2CWWH+9T61ieCnLtUaWBHMh/PNLoVCfMX/UFHj8/Pa5d5XYaqr3Yde7VDEAunl8nXXw9uTqu3vNkw7qYvhXFODaz4SnfWKkpVpOOoFxFcDzzwHjgJ3ZUVZ4FFjL3DhuXawoCTGnuvGfN8G7okjPa7qBx4Jb+n53COQto10x2WQZjkn5gDykNJXLMLyOnT8Ycc+/pkygTRwSyr9OPId11BfomdcuypSep54lpwxhbqgAQAXOCglWDxpY9cX6gk0qaSyzop/NlFQWaL6WmK7NoBq6WRXByFPlH7NqXcMS2SNdmz7ZDL5upSOWwIAbX5RMTjhvRgXtYeWXWF0Fw8A4FQtlYdfvLLCvHwOQgOPjIeqFMEcBJHpbSbOjEch8e6OMsmMofEr3SDh5+1OO2vHtWTzgHPFPWLxmpMoq5ano2FGloa8VBiWx+TTAayTow==
    OPENSEARCH_USER: AgCS27qrr8EP7QxaPIai87z0kgy3Efyj5FfAAN+AeTc9Ur2F/pXdbVv+7v4mBAxI28Z0PK+ax+19hyRt0FGNXHyyXqtMc0eERSrg6SaQ9qn6sBj7fLU56UP7GOtmIpmugNv8M4uOdODGrxbywjC5m0EO9xci3zTr7mvm7iOlUBPK0Q7kIhVQKdA2a2+wXqXNUZIkRSbxm7588Ka+nBbU0A7fp++KguZHmizF106iUQyMPk0GkML/8YraOVpCCByHwXwW3Sd+vAZQTLnlvGUqU5XzKQTOagyXI9xoHrxWGIC07qHQMCq50fCRzP584QVDEwjfFCpxDEVl25BtdfcSgYr5IcuDT6SPjMo8I+iSgUw+/deIq/GCyGoZ0d7Xyi98iXJu4TS/sIqwhmBP+EZnlHvt7zv3wN5xlQ2UpGC5YG3bZa9oOc21znOreC9P0WGFTGquMyPYKnWb/3Ap/4G/tOusKAbCC3S35W6IHtCqfYpScVIMUuRuIoovgIxlN+UGKOLBgGq2qi+ATIsBoEreHpwNKlc8kTphKAisn0d2a3msDD0idr0k9N3CPnG8kmc/1C7HzoCufiosdWYRT2aix5A2ToTdKNsLT0YBoglOIAMXedSuMQIfbfgCcJ2s/7hQh7SMJmgiI1a/uXbdLT79821p9XUEvdJzwwUl2YoHKtn54xzZR73kZjS4pgD1DNFwVXCyskHkug==
  template:
    metadata:
      creationTimestamp: null
      name: ml-secret
      namespace: ml
