---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ml-secret
  namespace: default
spec:
  encryptedData:
    OPENSEARCH_PASSWORD: AgBHuwrleFy8X83p7KmkAgqX1s+AAeZ+RgYY0EB4Ja0fCQcHD2e89Txga92KSLoavD3BjG4FI75lPF8C2BrBItYla9NwlTzZb49diat/yJUmUif2ofm5GAxRqOljM1rCKZUcJnKIDsnFlPgoX2CLRyLmKlSSwdEJxomYREMbPz18zsWwhIaRuHe6RSVs0p+yJ1W/W5dmu4M1SWu2gFipVDpud4ez0LVlEfsCtcMmk/qlw68krLNdIo39cY5FANQm4got5oshDaMXdLymwft2wUONQl4rk6oZbOMdUDvSkRxwVcyZ3UBEyP7+P+GwlG1Njraf5RapwN6NG484o1ZApXTssTkPSduNUzXPGC6csq1SYctJ7tfTB+83XG5eDfR5OfGGiQ6luuidAx9VHoJielE1JeIK+/XwJfqSkO8Ti+SMF8kKyzXkNwvTIvdkxThVXTmMXEsx1s8oVOgSpawT/YcV8N0vsOQP/toKM05oyZUc8AcHz039TUlC1wnN83+rGVcRX4i6MqAj6HeYs6iqTpAVhrNkyhcsAavcUFceSANuOznmqkqpofrWFGJDk/9MS9+bK8YGTC18WjTkmyeqf0YzgcMv3VkjqVCFce0PEs2cug+PnGZwSYaQWL7a3y/x+Yr+BAVzk2aq6oXY+0pviWPa2lcn+ef+UD+N2Lsj9V57SfMJV8gzAhfOfBQCsH3I0kJe5fKy+w==
    OPENSEARCH_USER: AgCFUWJ7JjYYEj8wtkLO5wskyJQKjW8w3ZgiYkQScnLnI+HuAMNfaCWxfn+NzZTYwZtnCbnALI5zQvE9Qyr90XaxXeaSy0BLOxQ6kiVRmRH3XNtzzNM7cWINYISyrqw8qQbCEc+CnzTuIo3/7ksEzkqafHJIKtH/ChMesxf9EaZyl/SPqGK+QHXYA715axDqQeD5HpBvz/J9GBnXCE7v1CFlRA5nvWhJcccgv+h563BRuS09P0AX/ajlJFsO1z5hcRPH5OtNhKmGFuyevl6eqDtrn1jtrlgpxec+0S+NP1AgGc/qdYTBebcqFksLmuzxPo8H+s5ZUZEgl3M/4kEMOv9FEAYCUuJXdtS4GOhseOllF76ijAUo/0925M2IW/wN8IRn1hiAAYWJU5frLyNbQ/y/sOOfKpLmLkWCzkWAAbbi+GRxitczHe3JFar/atqd70LIFbmCxg+5Q5dci/sZP9JCPO5hEpSJRMqxZjg6OtmlxqinlYzJRlGP58YXjdZ5gIWCUNuJySiRDvcPqSiFf/GGQ3xXGm7VJOKHzaPCkyBKmdCMgFusL/AfT23CaGmjbUt5w3GgSuIBdSct18EOKrnkrVMtlj73Hh9Sv4XIKRW3AQ1pntr7/uGyfAALHbCgHUKZjcyG3d17ezIrlcxdKlE+c86xnyugHzFMrdRGo9Pw8hGJYjjA6TGYpKmFFKpg6NLjVrCwwg==
  template:
    metadata:
      creationTimestamp: null
      name: ml-secret
      namespace: default
    type: Opaque
