apiVersion: v1
kind: Secret
metadata:
  name: logstash-secrets
  namespace: logging
type: Opaque
stringData:
  API_KEY: "4eOZNNV2d6yrn8SRIBg5ARuVguLvgNi9fziJ032A"
  OPENSEARCH_USER: "admin"
  OPENSEARCH_PASS: "admin"