apiVersion: batch/v1
kind: CronJob
metadata:
  name: spacetrack-ingest
  namespace: spacetrack
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: spacetrack-ingest
              image: viniciusadams91/spacetrack-ingest:1.0.0
              imagePullPolicy: IfNotPresent
              env:
                - name: SPACE_TRACK_IDENTITY
                  valueFrom:
                    secretKeyRef:
                      name: spacetrack-credentials
                      key: SPACE_TRACK_IDENTITY

                - name: SPACE_TRACK_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: spacetrack-credentials
                      key: SPACE_TRACK_PASSWORD

                - name: OPENSEARCH_HOST
                  valueFrom:
                    secretKeyRef:
                      name: opensearch-credentials
                      key: OPENSEARCH_HOST

                - name: OPENSEARCH_USER
                  valueFrom:
                    secretKeyRef:
                      name: opensearch-credentials
                      key: OPENSEARCH_USER

                - name: OPENSEARCH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: opensearch-credentials
                      key: OPENSEARCH_PASSWORD

                - name: OPENSEARCH_PORT
                  value: "9200"

                - name: OPENSEARCH_USE_SSL
                  value: "true"

                - name: OPENSEARCH_VERIFY_CERTS
                  value: "false"

                - name: OPENSEARCH_INDEX_PREFIX
                  value: "spacetrack-raw"

                - name: LOOKBACK_DAYS
                  value: "1"

                - name: BULK_BATCH_SIZE
                  value: "500"
              resources:
                requests:
                  cpu: "250m"
                  memory: "512Mi"
                limits:
                  cpu: "1"
                  memory: "1Gi"