apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-config
data:
  OPENSEARCH_HOST: "opensearch-cluster-master"
  OPENSEARCH_PORT: "9200"
  USE_SSL: "true"
  VERIFY_CERTS: "false"
  SOURCE_INDEX: "spacetrack-gp-2026.03.22"