apiVersion: batch/v1
kind: Job
metadata:
  name: ml-pipeline
  namespace: ml
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ml-pipeline
          image: viniciusadams91/ml-app:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ml-config
            - secretRef:
                name: ml-secret