apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opensearch-project.github.io/helm-charts/
    chart: opensearch
    targetRevision: 2.19.0
    helm:
      values: |
        clusterName: opensearch-cluster

        nodeGroup: master
        singleNode: true
        replicas: 1

        opensearchJavaOpts: "-Xms512m -Xmx512m"

        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "1Gi"

        persistence:
          enabled: false

        extraEnvs:
          - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
            value: "MyStrongTempPassword123!"

        service:
          type: ClusterIP

        config:
          opensearch.yml: |
            cluster.name: opensearch-cluster
            network.host: 0.0.0.0
            discovery.type: single-node

  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true