apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opensearch-project.github.io/helm-charts/
    chart: opensearch
    targetRevision: 2.13.0
    helm:
      values: |
        image:
          tag: "2.8.0"

        clusterName: opensearch-cluster
        nodeGroup: master
        singleNode: true
        replicas: 1

        opensearchJavaOpts: "-Xms512m -Xmx512m"

        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "1Gi"

        persistence:
          enabled: true
          storageClass: local-path
          accessModes:
            - ReadWriteOnce
          size: 20Gi

        extraEnvs:
          - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
            value: "MyStrongTempPassword123!"
          - name: DISABLE_INSTALL_DEMO_CONFIG
            value: "true"

        service:
          type: ClusterIP

        secretMounts:
          - name: opensearch-certs
            secretName: opensearch-certs
            path: /usr/share/opensearch/config/certs

        config:
          opensearch.yml: |
            cluster.name: opensearch-cluster
            network.host: 0.0.0.0
            discovery.type: single-node

            plugins.security.ssl.transport.pemcert_filepath: certs/node.pem
            plugins.security.ssl.transport.pemkey_filepath: certs/node-key.pem
            plugins.security.ssl.transport.pemtrustedcas_filepath: certs/root-ca.pem
            plugins.security.ssl.transport.enforce_hostname_verification: false

            plugins.security.ssl.http.enabled: true
            plugins.security.ssl.http.pemcert_filepath: certs/node.pem
            plugins.security.ssl.http.pemkey_filepath: certs/node-key.pem
            plugins.security.ssl.http.pemtrustedcas_filepath: certs/root-ca.pem

            plugins.security.allow_default_init_securityindex: true
            plugins.security.authcz.admin_dn:
              - "CN=admin,OU=OpenSearch,O=ViniLab,L=Dublin,ST=Dublin,C=IE"
            plugins.security.nodes_dn:
              - "CN=node,OU=OpenSearch,O=ViniLab,L=Dublin,ST=Dublin,C=IE"

  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true