apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opensearch-credentials
  namespace: logstash-spacetrack
spec:
  encryptedData:
    OPENSEARCH_PASSWORD: AgBCfVnCKWG/hdakUYWOfDI7sA92PoWdRLhtsMw6iqCr5nR3UCalKLqg5vM89R68ZdJHlgD5/nn5XPwK5lTCPkeCnNbCU9Y4YRjOOfsw5ll4IJ/S64uDvoM9MO81VWM5/LevXaM5k7pI7/cHdCU1W2rKT1wfNeFxi9aqv2tMRT7QW+h5/vBWLdYZylC/bnZLUlY48QQTo9OiTNKjkU6Kb+u0oW0f5tM7TQvd/THWDsXvaaKfb8nNY6Dh8EnSxN9iJYymh6EsLYw7NWqGSiPz9bWJmtGkVavxDc8g+dCU6xRW+Nt7hiVFRJahjuXn0Zy26xuH9wARVCAL8sygVYQGQQaGte4j4QAGbiFAJvhtXi2Nc0LZbgZV5JBmWNrhk0rym1ji/oqaMw38tBth07mHAdKblipBl+4fcVM6RFeIp0advQihtvJfMMYvDM7nH3uOR5tHFKI5BJrQk/HSki+nv8QvKHna8yKFFeH1dMWm4NgK6LoxudWMpp/TbYJU8LNgYDjTjrIZZLyXIUIXGhJ006Hmwpo0XlpoVrO0kiKLdjNRlf/0mEWjTtcdiRWqErgEDwqV7wUdxGXsNgw5dI4s5lI+VTEXw4Xr/Kw5ZFsLWsMajiWWZIssZZ2gVQtQb2qy/Q+ugxP1j/5m1JR148WSgJQI7OVAtwuIjGmfCr7QQsAWMz+xHzJCOBl4r9yRFm6QogY6W01XBw==
    OPENSEARCH_USERNAME: AgB6FXrjTdqjoTD7tTxyocYNXFvG7BpSizH63nO5NP8W/sSXLsOX3+eb3sf/lbQuah4trTaVTeWdlc05meQ4aQGc6HtzGVxX9ep3SCeNkgpiLRN1gbQ0QZNVC8jwlgRGEohWLmyvb5XVnU2v9vwSw2F3VxoJ4Ogjhq5aMfPI107b0YM/kob71A7qA3HtlB6A2av4/rfPw7IkdbU1e+qoL+vV6DsJ1p6qqjke2vO7/KjKJU65GeRkrQqnZY60bTeaZET9Y/5YfwimaEYR7eFE/paqGgeziC7CXZrMuiNYlZbG89JNYz6I5Vw/EpDXf5o9V0CZWL9wRe48so2KqN5jsibi9L1mHF5mVKfQDrTUVxKFkpMSnT3h9CYTFMPVPkXPAFONJBeru06MqyxViOvPK3GwPWtly/NgR7HcbKaRKHQhfUO1HavgBcuT2/loyGhP/Ijf4uPDDkO0OgzbruLGTOoDOYY5IrwwY8sbE2Zqc4boI1HVTwqxYSnn3TqF+1TPXdP5YbRiISKBlDzeej5NxDHJnzglRCpQE7WvFtODXt4wbogmZUJHjPmsC4n2slw/SsZQWD6E5uBYd8kOheoIwyQwYsknvdMipguEukOvNDLUFrUP9OBmCuERG9FK9tvtWYMjzrYqvWGF/mZRvH/v9fDSBV9DmnD/KNzflCqxUlNXbmPyXmaSZVEV1V2QjwXsejdLOWy90Q==
  template:
    metadata:
      creationTimestamp: null
      name: opensearch-credentials
      namespace: logstash-spacetrack
    type: Opaque
