apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: spacetrack-credentials
  namespace: logstash-spacetrack
spec:
  encryptedData:
    SPACE_TRACK_IDENTITY: AgBgKV+78W6DgYrP1TT9Ztc2PYePooiyTyViBdiT1K1Ffmd8B6g/YZYOE4Z1AGHG0Uz/5i+cxBL1U2/lV2GGWj5bAL71kzjRqJLiCJDuvEzbNQIkHx20+WDjsG/22IKap5C/29Sgg3TV3f5/wZCZF8K8FzVs/LqKEzIlsjJ0GEqdeN9eEtolK+sIX+HVn/j6oVFTJ5619y/txVz+tfUOLkb4yYHNf3W/g7llFmzYTS06taIXrVpb3KPKutRwDsEc5tNkl1Zpa6/0qMumiZGstLYKwyy/NHbnRWtb4OuOJ8qlwyXHt2Cv+YowDYwxUl3NEoyP678SXaR+7OFcRIih3ss2GcnG9ajZh7OpUC7HZ23b7z+rzStebMQtwPkj8Ps9+fK82LREuscoK24dsHB+lExZ7AWh4ff9LTAfrPZac8WsHqc6KqfwOaL6ZPIvzmdSduYxej98C6v+n2/f//NuDUT68Jx7YrTM+qIYg5y0KYkA5N0uj+aftfcuslA5cGHcWXUyi7TMKPT/Sp3AQAracB1rRw8P0GU8ZeZ8QiUkZM3VrrpbcxoPJmGeyEcGRuctcfLr/21mQ6imfERoD2BG8PjP6D1oNoJHCIFRHd3Ts1awzh4QwvTSRtnYU7oiSatbAK/Jhe57qe6ggj/Duc/RWekyPgSWAl4UGm6JuPcnx++Ht3+o9XgUaEZ6mZ/kSTfVMMLn94IGjpjilV8J1o7D4jv7AfVarPhGRXhK
    SPACE_TRACK_PASSWORD: AgCkgz432eckmZCng/BfY5g+Ep5Ce120jFmAc2O7dHglDi2+tkZK4Pq8r1hr8UyyvwIiDebW2+5dADK0s0XYDbacd/eIPX7oOa0CxmYJilxeD0x37+zgXg9JiCDKApS1Uq5YLMap+xDRkGy1gBS5VzBokvjlDQZD3fMk4mHmtHp6qcTGJnHdktfJp4yY4Ih1BRW7vcr0erS3z4BM8K3QNosegctM9mkiMmNf/tAAMBl2DBud96kXX7N0y1oTiBotLLz7ec0Xbh1KkTmjSvRAu65Ar9ZY1NxSTRrGmb1rplxG+zz8G6wAqNcdB98QED9ewDROo5imDx85cA++FuOeNM8R7+AxNTvI4pTcxyPjIb6a9CkVc7vUDa79B6vQwfpcfMGyPpJAY2QgQIhdDGyVzeAivfhokOZBHnr/IAL6S1EyYnLAXrZp8pvQgSGPzNI7eiccUgHoJ0PrKnC6ngfMwboKyxpa6TVZPs4e6HjU3AeuyKOsoraFCztagfhX2pyTFxwIjA8GssdohhgEPvB7kMwTxM05mPooXF8dEzoQbgXvMPcpbKL1KHXueFhnDAg+mjWhejbHAIMYAyGRsvOE24ZtIjoOo3VlVrzcEIBoBBk4XR5ud3YqOcHAzOFin3bzn8Y7yz6+iIYeCutpUSDDFjHdg4K42GIRnT2wouXMSg2it3kV9r5D619z3OPbL7+cXKMZpW1HiDp89Q2gJANfw22s/7jj
  template:
    metadata:
      creationTimestamp: null
      name: spacetrack-credentials
      namespace: logstash-spacetrack
    type: Opaque
