---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: spacetrack-credentials
  namespace: spacetrack
spec:
  encryptedData:
    SPACE_TRACK_IDENTITY: AgBLj8xzdVKnpDMFZBLuVnKzHiEMWptmTLpBnDA3k5bFtmI2SJrsclnIl6E1JhgXjSSBiSilSYzzgwDaMHEhU0n60Js293hV35wO3kIyNyu5QKNh+1u/RwRtRGODYlhoRiG/pRr+1Y13+PUdeSseZHOg/n4EHIZve7WkmruwnvMRLFn6laV4/+V0R6KK3dOb/XrivhGCgM6v3V4JLRrYnOcnuB5vUkOFucpTD60QvBl2kraxN7QCcc5XO7/Ag+kbEPjbWWrlRXFjTjmkN9G/OB4z+e8cdxUJHo5ZMEK+vhCHOak9zmHXEfgGvRlv+VvL2qOJ5F0FhWkJmSoT5PjFE7Y1wcAZSiMz2edOXJ9L0PG8F6ZEAY6qEfVnm2MfE+tBA3tMhZDwX++xCEYrfDke/OCm/qK+rid/A0wRd1dcEgPiML0TFYsDohqeAEm8BICTdBQ9yZG6egyPaNJEBbT3mHUYFLns3dbrW8oj3pk0/aUidgzUyFMFeam0V+qh/t9Zycj1Srzg/lQVNhLO/+LxWO+rwnD/C3ZYz+US0iAXr2/S6H3lhcchDb3xtlD0suDVe0+iZy4bMsjagmy+hTbEaw7QaNZljiH3dUEyGIOD/w9NDTswipZ/U53J7aCysQEMeX/f796YfcOuBsDlGUcROulN7DoBSX4lGBBPmR0b0dUsdrDuDHZebdCysNd+6CgQ/S82BW6/sWPGXAgsBMgNx4Mp6lKDEUaqecg4
    SPACE_TRACK_PASSWORD: AgA+SuIRVUyQE/kvRNf6QbWBkWw2ezx307rie+a61OwbeZ4hF2DZjMzrAidrdjCqDTIa1yUOvhRZa5dldFzN1uHTrYZdXm57X6+HYKJMNgBmLQ9BhUZ2XnA6A3q9gQCMYXF9hqXdV4I3gt/+9cifLnd0bwm1fsiFGkOLkVt+tlXp8YHLzCxNJnqdz4vo2JLEFCJZpDPIlCK86XP//AgpGAJ81ThxinpD+A4tI4ATzWGB41G6CaU4O9kIhNdgkLJ/1kXQrYKfkS/w6yNFLumAiZjIOII3kptp8snvHO3gMtHxorkUcwwOLEXlFvIbT05Yu/RIJAaOgNPZ7bLMO7f6x+y4COEc4xYx4UWmfpjCU6fepIK4o/itADZMrfno6mKILcCavas4vkDJOxxMCh9d7zG92SFFeBltNWv5Cl+OlWzFVe0jH1HPp3w7doR8yeJo4DZRp+eUmRqgfy1cITdoNYJebyU6cO8vtb0DKARBf5Y76QIbOBlmHS2erTZsBKilHB3ZrVFIbw88RBLqhkmxPVFsbhAUTlSU4iddUpmMuZIj1jBezYO/0rlCOQ9lvOofY5LYIaLpv+zqRPUJ0i96r0vPHk3kXoc4ezwgH3gPfngrIy9lotTfJ+p4NcBJGbbFSfBlfxoHmTMRj0om8FaqQBbZzKbcg4heu0w8xWQBfcv0MG38vqhjCY8w70ZT2bZOGtOIPMrUjMLqsGQUQt3M6jlKUMa0
  template:
    metadata:
      creationTimestamp: null
      name: spacetrack-credentials
      namespace: spacetrack
