---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: spacetrack-credentials
  namespace: spacetrack-collector
spec:
  encryptedData:
    SPACE_TRACK_IDENTITY: AgBFBcEhaqqZj776r5IjVAblbWm7lNsXKC6rJRvMTO6omnb6Pg20hXYxEYfPPd8tRzJYvpkNTJYl93T6gNtQkLunSIsVbiiflCmOEKk4uIIhFpO27VbUTDE6EDQa3qeqA5WN8jc1Mi0xmTcMrFRMABp640imS7Elcv9sph0fLkCHeIglZFMheCQxJ0JKQvxz1vQDyUsv+OJH4vX62PrKZgKxAX5v96NPd95MSRo3xAYTcxFHTzvt0Q6kmaRc53KlSoZ63Jam1AE0IXVXfZ/BNOySR1BQnb+YSsj0nILdqHZc7pXH1mIf0QfOWnUMTUUMITqEavCG9SBzZmgwUJJTBcNcIJDt29gasWFec40pzqaBATU/4HARVSs9TSnvs08L+kRZ+JmijZ6msQ0gs8m8WrH6gPpLIca5gb0CB2e2JB4Oypl7QisytD23yc2dErkJYmym6AAZOD+6n+ILTX9KB85Of7Das+5gjGwBmH/D+QkpxNNkuojesAuw5HggzNDe4KjAn34w6Cm2uItwKjL4JVWJvoU9NA+SRZnk9sVUgqYzOXWt1CDuaQg/es9Qm81+2OzqpIGlpYBTxhtM2z7Mw+IqvX4vBdgvSS73YKWuwffP6baFi4nY9g7MeJVcpsw90Sn6/FafPhZfdRqOahTX7SY5dhZuC/xUQLxe8IdNVYlLIfpEKfJYxVO6aa+mTAYEOUHqKPdV/9X7Umdl4Fyox4jxmTOFfgIL5wM=
    SPACE_TRACK_PASSWORD: AgB/9ZYDKH1VKenrY/w5pBRoXKrWQLj3vzAzi/ND4wPGW3gP44D4jlxEOTcG+e9IdayqloUPP2N7Q/aaHj2xndDJJ7t0G0RjNimT6bZPDgYnDJ+4bXY183LkRKtfIz+y0oLF3+vq+jeNSPUExBdM0vroxJwAGMT0Tr8O4pGF5uVI/LgV6dQvAOjltFM82bz3ZipaeU/292ocD9ZTcVXuWO90QSmahW0zphigRxklzAJ7g/hmqYFSw6u4hV/pUQOboC+jTJT36Oxnwu8g1+UPl233JUfzkANR+aT6mNai8n4gorQRSvNn+lKIAtcBMt1JZufHt8xzR1zL4mVMUZvPpwab2GwuuuU5M2jc5m97x39odlByyLwPBcLBsW6aY+rHJfQ9RK4azSFduV0LuPbvUwA5UGdHB4V0LESAcqL/yyE54q0y+tWUp69JYz5EYIHb9esaJWXB8f9sMmjo1xwZyO5gPhCUtogNeAadmBBtq1PvKjxZ/bWW99pvVyTkqThetp++hOQSxGqBwIJu0gyPQzsUR6bxepNmNRQ9mFy12hJH4wIMPojLrDPltLplRS97rXuFyu1r5qK7vQoR3wmQAKTX/nHB/RqMM6yHl0SIPdJFbXX2FM0zv78CMzR33dV/iKtsQGnyu9utadmiXvChOgKkbPcnP0+gMqbKtZ+HJRSW4MSt/n6Bg7VUpE+d4aLkOYEWUh7MyeJ0B7WbqRR5fLjaLCeZ
  template:
    metadata:
      creationTimestamp: null
      name: spacetrack-credentials
      namespace: spacetrack-collector
    type: Opaque
